### ISSUE TITLE
Support specifying multiple uriPath with different configurations

### ISSUE THREAD

**Issue by sunilraok** [dropwizard/dropwizard-web#32]
I have a requirement of returning different CSP headers based on the `uriPath`. Here is an example configuration I want to use.

```
web1:
  uriPath: /api1
  csp:
    enabled: true
    policy: <csp policies 1>

web2:
  uriPath: /api2
  csp:
    enabled: true
    policy: <csp policies 2>
```

I tried the above with the below bundle configuration, but only `web2` configuration seems to be taking effect. Is there a way I can get it working, and if not, can we support this?

```
bootstrap.addBundle(new WebBundle<ExampleConfiguration>() {
  @Override
  public WebConfiguration getWebConfiguration(final ExampleConfiguration configuration) {
    return configuration.getWeb1Configuration();
  }
});

bootstrap.addBundle(new WebBundle<ExampleConfiguration>() {
  @Override
  public WebConfiguration getWebConfiguration(final ExampleConfiguration configuration) {
    return configuration.getWeb2Configuration();
  }
});
```
